/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/watch.glb 
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

import { useSnapshot } from 'valtio'
import state from '../store/index.js'

const Watch = (props) => {
  const { nodes, materials } = useGLTF('/models/watch.glb')
  const snap = useSnapshot(state)

 
  nodes.wristBand.material.color.set(snap.wristBandColor)
  nodes.dial.material.color.set(snap.dialColor)
  nodes.pointer1.material.color.set(snap.pointerColor)
  nodes.pointer2.material.color.set(snap.pointerColor)


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle007.geometry} material={materials.metal} position={[-0.988, 3.686, 0]} rotation={[0.029, 0, -Math.PI / 2]} scale={0.161}>
        <mesh geometry={nodes.dial.geometry} material={materials.dial} position={[-0.927, 6.127, 0]} rotation={[0, 0, Math.PI / 2]} scale={5.973} />
        <mesh geometry={nodes.frame.geometry} material={materials.metal} position={[1.256, 6.127, 0]} rotation={[0, 0, Math.PI / 2]} scale={6.199} />
        <mesh geometry={nodes.frameBack.geometry} material={materials.metal} position={[1.006, 6.127, 0]} rotation={[0, 0, Math.PI / 2]} scale={5.973} />
        <mesh geometry={nodes.glass.geometry} material={materials.glass} position={[-0.937, 6.127, 0]} rotation={[0, 0, Math.PI / 2]} scale={5.973} />
        <mesh geometry={nodes.pointer1.geometry} material={materials.pointer} position={[-0.927, 6.127, 0]} rotation={[0, 0, Math.PI / 2]} scale={6.199} />
        <mesh geometry={nodes.pointer2.geometry} material={materials.pointer} position={[-1.107, 6.127, 0]} rotation={[2.262, 0, Math.PI / 2]} scale={6.199} />
        <mesh geometry={nodes.wristBand.geometry} material={materials.silikon} position={[1.256, 6.127, 0]} rotation={[0, 0, Math.PI / 2]} scale={[5.019, 6.199, 6.199]} />
        <mesh geometry={nodes.wristJoints.geometry} material={materials.metal} position={[1.256, 6.127, 6.59]} scale={[6.199, 5.019, 6.199]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/watch.glb')
export default Watch
